Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'/tmp/try_flags_5wnh0voh.c:4:19: fatal error: cudnn.h: No such file or directory\ncompilation terminated.\n'
Mapped name None to device cuda: GeForce GTX 1080 (0000:02:00.0)
vafnet is not installed yet! Trying to call directly from source...
done.
Traceback (most recent call last):
  File "training.py", line 139, in <module>
    train_test_set = load_data()
  File "training.py", line 38, in load_data
    data = pd.DataFrame.from_csv(path=DATA_PATH, header=None, index_col=0)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 1261, in from_csv
    infer_datetime_format=infer_datetime_format)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'Relation Network (Undirected).data' does not exist
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'/tmp/try_flags_kv3oqe60.c:4:19: fatal error: cudnn.h: No such file or directory\ncompilation terminated.\n'
Mapped name None to device cuda: GeForce GTX 1080 (0000:02:00.0)
vafnet is not installed yet! Trying to call directly from source...
done.
Traceback (most recent call last):
  File "training.py", line 139, in <module>
    train_test_set = load_data()
  File "training.py", line 39, in load_data
    data = data.as_matrix().astype(np.float32)
ValueError: could not convert string to float: '?'
